### ISSUE TITLE
plotlyrs and plotly.js

### ISSUE THREAD

**Issue by wangjiawen2013** [plotly/plotly.rs#221]
Hi,
[charts-rs](https://github.com/vicanso/charts-rs) is a charting library implemented in pure rust. [Charming](https://github.com/yuankunzhang/charming) is a powerful and versatile chart rendering library for Rust based on echart.js.  What's the relationship between plotly.rs and plotly.js ? Is it in pure rust ?

**Comment by andrei-ng** [comment]
Both `charts-rs` and `charming` are generating HTML code that calls the JavaScript [Apache ECharts](https://echarts.apache.org/en/index.html) library.

In a similar fashion, `plotly-rs` generates HTML code that calls the `plotly.js` library. 

The philosophy is the same. None are pure rust plotting libraries. They are pure rust HTML generators. They rely on a JavaScript backend service to do the actual plotting.

**Comment by wangjiawen2013** [comment]
Thanks!
Now I have another question. It is said that we should install python plotly in order to support jupyter, what's the relationship between python plotly and rust plotly ? Does plotly.rs depend on python plotly ?
![image](https://github.com/user-attachments/assets/ce68dd00-0c31-4650-9b45-2323406420b4)

**Comment by andrei-ng** [comment]
`plotly.rs` does not depend on `plotly python`. All dependencies for `plotly.rs` are in `Cargo.toml`.
I haven't developed that integration myself, it seems that `plotly python` is needed in Jupyter in order to add (I suspect) the javascript capabilites to Jupyter to be able to parse and show the generated `plotly-rs` HTML code as plotly plots.
